type grbModel
type grbEnv

(* version numbers *)
val grb_VERSION_MAJOR     : int
val grb_VERSION_MINOR     : int
val grb_VERSION_TECHNICAL : int

(* default and max priority for Compute Server jobs *)
val grb_DEFAULT_CS_PRIORITY : int
val grb_MAX_CS_PRIORITY     : int

(* error codes *)
type grbError =
  | GRB_ERROR_OUT_OF_MEMORY
  | GRB_ERROR_NULL_ARGUMENT
  | GRB_ERROR_INVALID_ARGUMENT
  | GRB_ERROR_UNKNOWN_ATTRIBUTE
  | GRB_ERROR_DATA_NOT_AVAILABLE
  | GRB_ERROR_INDEX_OUT_OF_RANGE
  | GRB_ERROR_UNKNOWN_PARAMETER
  | GRB_ERROR_VALUE_OUT_OF_RANGE
  | GRB_ERROR_NO_LICENSE
  | GRB_ERROR_SIZE_LIMIT_EXCEEDED
  | GRB_ERROR_CALLBACK
  | GRB_ERROR_FILE_READ
  | GRB_ERROR_FILE_WRITE
  | GRB_ERROR_NUMERIC
  | GRB_ERROR_IIS_NOT_INFEASIBLE
  | GRB_ERROR_NOT_FOR_MIP
  | GRB_ERROR_OPTIMIZATION_IN_PROGRESS
  | GRB_ERROR_DUPLICATES
  | GRB_ERROR_NODEFILE
  | GRB_ERROR_Q_NOT_PSD
  | GRB_ERROR_QCP_EQUALITY_CONSTRAINT
  | GRB_ERROR_NETWORK
  | GRB_ERROR_JOB_REJECTED
  | GRB_ERROR_NOT_SUPPORTED
  | GRB_ERROR_EXCEED_2B_NONZEROS
  | GRB_ERROR_INVALID_PIECEWISE_OBJ
  | GRB_ERROR_UPDATEMODE_CHANGE
  | GRB_ERROR_CLOUD
  | GRB_ERROR_MODEL_MODIFICATION

(* constraint senses *)
type grbSense = GRB_LESS_EQUAL | GRB_GREATER_EQUAL | grb_EQUAL

(* variable types *)
type grbVartype = GRB_CONTINUOUS | GRB_BINARY | GRB_INTEGER | GRB_SEMICONT | GRB_SEMIINT

(* objective sense *)
type grbObjsense = GRB_MINIMIZE | GRB_MAXIMIZE

(* SOS types *)
type grbSostype = GRB_SOS_TYPE1 | GRB_SOS_TYPE2

(* Numeric constants *)
val grb_INFINITY       : int
val grb_UNDEFINED      : int (* 1e100 ? *)
val grb_MAXINT         : int

(* Limits *)
val grb_MAX_NAMELEN    : int
val grb_MAX_STRLEN     : int
val grb_MAX_CONCURRENT : int

(* Model attributes *)
type charAttr =
  | GRB_CHAR_ATTR_QCSENSE
  | GRB_CHAR_ATTR_SENSE
  | GRB_CHAR_ATTR_VTYPE

type boolAttr =
  | GRB_INT_ATTR_IIS_MINIMAL
  | GRB_INT_ATTR_IIS_LB
  | GRB_INT_ATTR_IIS_UB
  | GRB_INT_ATTR_IIS_CONSTR
  | GRB_INT_ATTR_IIS_SOS
  | GRB_INT_ATTR_IIS_QCONSTR
  | GRB_INT_ATTR_IIS_GENCONSTR

type dblAttr =
  | GRB_DBL_ATTR_DNUMNZS
  | GRB_DBL_ATTR_DSTART
  | GRB_DBL_ATTR_LB
  | GRB_DBL_ATTR_MAX_BOUND
  | GRB_DBL_ATTR_MAX_COEFF
  | GRB_DBL_ATTR_MAX_OBJ_COEFF
  | GRB_DBL_ATTR_MAX_RHS
  | GRB_DBL_ATTR_MIN_BOUND
  | GRB_DBL_ATTR_MIN_COEFF
  | GRB_DBL_ATTR_MIN_OBJ_COEFF
  | GRB_DBL_ATTR_OBJ
  | GRB_DBL_ATTR_OBJCON
  | GRB_DBL_ATTR_PSTART
  | GRB_DBL_ATTR_QCRHS
  | GRB_DBL_ATTR_RHS
  | GRB_DBL_ATTR_START
  | GRB_DBL_ATTR_UB
  | GRB_DBL_ATTR_VARHINTVAL

type intAttr =
  | GRB_INT_ATTR_BRANCHPRIORITY
  | GRB_INT_ATTR_GENCONSTRTYPE
  | GRB_INT_ATTR_IS_MIP
  | GRB_INT_ATTR_IS_QCP
  | GRB_INT_ATTR_IS_QP
  | GRB_INT_ATTR_LAZY
  | GRB_INT_ATTR_MODELSENSE
  | GRB_INT_ATTR_NUMBINVARS
  | GRB_INT_ATTR_NUMCONSTRS
  | GRB_INT_ATTR_NUMGENCONSTRS
  | GRB_INT_ATTR_NUMINTVARS
  | GRB_INT_ATTR_NUMNZS
  | GRB_INT_ATTR_NUMPWLOBJVARS
  | GRB_INT_ATTR_NUMQCNZS
  | GRB_INT_ATTR_NUMQCONSTRS
  | GRB_INT_ATTR_NUMQNZS
  | GRB_INT_ATTR_NUMSOS
  | GRB_INT_ATTR_NUMVARS
  | GRB_INT_ATTR_PWLOBJCVX
  | GRB_INT_ATTR_VARHINTPRI

type strAttr =
  | GRB_STR_ATTR_CONSTRNAME
  | GRB_STR_ATTR_GENCONSTRNAME
  | GRB_STR_ATTR_MODELNAME
  | GRB_STR_ATTR_QCNAME
  | GRB_STR_ATTR_SERVER
  | GRB_STR_ATTR_VARNAME
