type grbModel
type grbEnv

(* version numbers *)
val grb_VERSION_MAJOR     : int
val grb_VERSION_MINOR     : int
val grb_VERSION_TECHNICAL : int

(* default and max priority for Compute Server jobs *)
val grb_DEFAULT_CS_PRIORITY : int
val grb_MAX_CS_PRIORITY     : int

(* error codes *)
type grbError =
  | GRB_ERROR_OUT_OF_MEMORY
  | GRB_ERROR_NULL_ARGUMENT
  | GRB_ERROR_INVALID_ARGUMENT
  | GRB_ERROR_UNKNOWN_ATTRIBUTE
  | GRB_ERROR_DATA_NOT_AVAILABLE
  | GRB_ERROR_INDEX_OUT_OF_RANGE
  | GRB_ERROR_UNKNOWN_PARAMETER
  | GRB_ERROR_VALUE_OUT_OF_RANGE
  | GRB_ERROR_NO_LICENSE
  | GRB_ERROR_SIZE_LIMIT_EXCEEDED
  | GRB_ERROR_CALLBACK
  | GRB_ERROR_FILE_READ
  | GRB_ERROR_FILE_WRITE
  | GRB_ERROR_NUMERIC
  | GRB_ERROR_IIS_NOT_INFEASIBLE
  | GRB_ERROR_NOT_FOR_MIP
  | GRB_ERROR_OPTIMIZATION_IN_PROGRESS
  | GRB_ERROR_DUPLICATES
  | GRB_ERROR_NODEFILE
  | GRB_ERROR_Q_NOT_PSD
  | GRB_ERROR_QCP_EQUALITY_CONSTRAINT
  | GRB_ERROR_NETWORK
  | GRB_ERROR_JOB_REJECTED
  | GRB_ERROR_NOT_SUPPORTED
  | GRB_ERROR_EXCEED_2B_NONZEROS
  | GRB_ERROR_INVALID_PIECEWISE_OBJ
  | GRB_ERROR_UPDATEMODE_CHANGE
  | GRB_ERROR_CLOUD
  | GRB_ERROR_MODEL_MODIFICATION

(* constraint senses *)
type grbSense = GRB_LESS_EQUAL | GRB_GREATER_EQUAL | GRB_EQUAL

(* variable types *)
type grbVartype = GRB_CONTINUOUS | GRB_BINARY | GRB_INTEGER | GRB_SEMICONT | GRB_SEMIINT

(* objective sense *)
type grbObjsense = GRB_MINIMIZE | GRB_MAXIMIZE

(* SOS types *)
type grbSostype = GRB_SOS_TYPE1 | GRB_SOS_TYPE2

(* Numeric constants *)
val grb_INFINITY       : float
val grb_UNDEFINED      : float (* 1e100 ? *)
val grb_MAXINT         : int

(* Limits *)
val grb_MAX_NAMELEN    : int
val grb_MAX_STRLEN     : int
val grb_MAX_CONCURRENT : int

(* Model attributes *)
type charAttr =
  | GRB_CHAR_ATTR_QCSENSE
  | GRB_CHAR_ATTR_SENSE
  | GRB_CHAR_ATTR_VTYPE

type dblAttr =
  | GRB_DBL_ATTR_BARX
  | GRB_DBL_ATTR_BOUND_SVIO
  | GRB_DBL_ATTR_BOUND_SVIO_SUM
  | GRB_DBL_ATTR_BOUND_VIO
  | GRB_DBL_ATTR_BOUND_VIO_SUM
  | GRB_DBL_ATTR_CDUALNORM
  | GRB_DBL_ATTR_COMPL_VIO
  | GRB_DBL_ATTR_COMPL_VIO_SUM
  | GRB_DBL_ATTR_CONSTR_RESIDUAL
  | GRB_DBL_ATTR_CONSTR_RESIDUAL_SUM
  | GRB_DBL_ATTR_CONSTR_SRESIDUAL
  | GRB_DBL_ATTR_CONSTR_SRESIDUAL_SUM
  | GRB_DBL_ATTR_CONSTR_SVIO
  | GRB_DBL_ATTR_CONSTR_SVIO_SUM
  | GRB_DBL_ATTR_CONSTR_VIO
  | GRB_DBL_ATTR_CONSTR_VIO_SUM
  | GRB_DBL_ATTR_DNUMNZS
  | GRB_DBL_ATTR_DSTART
  | GRB_DBL_ATTR_DUAL_RESIDUAL
  | GRB_DBL_ATTR_DUAL_RESIDUAL_SUM
  | GRB_DBL_ATTR_DUAL_SRESIDUAL
  | GRB_DBL_ATTR_DUAL_SRESIDUAL_SUM
  | GRB_DBL_ATTR_DUAL_SVIO
  | GRB_DBL_ATTR_DUAL_SVIO_SUM
  | GRB_DBL_ATTR_DUAL_VIO
  | GRB_DBL_ATTR_DUAL_VIO_SUM
  | GRB_DBL_ATTR_FARKASDUAL
  | GRB_DBL_ATTR_FARKASPROOF
  | GRB_DBL_ATTR_INT_VIO
  | GRB_DBL_ATTR_INT_VIO_SUM
  | GRB_DBL_ATTR_ITERCOUNT
  | GRB_DBL_ATTR_KAPPA
  | GRB_DBL_ATTR_KAPPA_EXACT
  | GRB_DBL_ATTR_LB
  | GRB_DBL_ATTR_MAX_BOUND
  | GRB_DBL_ATTR_MAX_COEFF
  | GRB_DBL_ATTR_MAX_OBJ_COEFF
  | GRB_DBL_ATTR_MAX_QCCOEFF
  | GRB_DBL_ATTR_MAX_QOBJ_COEFF
  | GRB_DBL_ATTR_MAX_RHS
  | GRB_DBL_ATTR_MIN_BOUND
  | GRB_DBL_ATTR_MIN_COEFF
  | GRB_DBL_ATTR_MIN_OBJ_COEFF
  | GRB_DBL_ATTR_MIN_QCCOEFF
  | GRB_DBL_ATTR_MIN_QOBJ_COEFF
  | GRB_DBL_ATTR_MIN_RHS
  | GRB_DBL_ATTR_MIPGAP
  | GRB_DBL_ATTR_N2KAPPA
  | GRB_DBL_ATTR_NODECOUNT
  | GRB_DBL_ATTR_OBJ
  | GRB_DBL_ATTR_OBJBOUND
  | GRB_DBL_ATTR_OBJBOUNDC
  | GRB_DBL_ATTR_OBJCON
  | GRB_DBL_ATTR_OBJN
  | GRB_DBL_ATTR_OBJNABSTOL
  | GRB_DBL_ATTR_OBJNCON
  | GRB_DBL_ATTR_OBJNRELTOL
  | GRB_DBL_ATTR_OBJNVAL
  | GRB_DBL_ATTR_OBJNWEIGHT
  | GRB_DBL_ATTR_OBJVAL
  | GRB_DBL_ATTR_OPENNODECOUNT
  | GRB_DBL_ATTR_PI
  | GRB_DBL_ATTR_POOLOBJBOUND
  | GRB_DBL_ATTR_POOLOBJVAL
  | GRB_DBL_ATTR_PREFIXVAL
  | GRB_DBL_ATTR_PSTART
  | GRB_DBL_ATTR_QCPI
  | GRB_DBL_ATTR_QCRHS
  | GRB_DBL_ATTR_QCSLACK
  | GRB_DBL_ATTR_RC
  | GRB_DBL_ATTR_RHS
  | GRB_DBL_ATTR_RUNTIME
  | GRB_DBL_ATTR_SA_LBLOW
  | GRB_DBL_ATTR_SA_LBUP
  | GRB_DBL_ATTR_SA_OBJLOW
  | GRB_DBL_ATTR_SA_OBJUP
  | GRB_DBL_ATTR_SA_RHSLOW
  | GRB_DBL_ATTR_SA_RHSUP
  | GRB_DBL_ATTR_SA_UBLOW
  | GRB_DBL_ATTR_SA_UBUP
  | GRB_DBL_ATTR_SLACK
  | GRB_DBL_ATTR_START
  | GRB_DBL_ATTR_UB
  | GRB_DBL_ATTR_UNBDRAY
  | GRB_DBL_ATTR_VARHINTVAL
  | GRB_DBL_ATTR_VDUALNORM
  | GRB_DBL_ATTR_X
  | GRB_DBL_ATTR_Xn
  | GRB_DBL_ATTR_XN

type intAttr =
  | GRB_INT_ATTR_BARITERCOUNT
  | GRB_INT_ATTR_BOUND_SVIO_INDEX
  | GRB_INT_ATTR_BOUND_VIO_INDEX
  | GRB_INT_ATTR_BRANCHPRIORITY
  | GRB_INT_ATTR_CBASIS
  | GRB_INT_ATTR_COMPL_VIO_INDEX
  | GRB_INT_ATTR_CONSTR_RESIDUAL_INDEX
  | GRB_INT_ATTR_CONSTR_SRESIDUAL_INDEX
  | GRB_INT_ATTR_CONSTR_SVIO_INDEX
  | GRB_INT_ATTR_CONSTR_VIO_INDEX
  | GRB_INT_ATTR_DUAL_RESIDUAL_INDEX
  | GRB_INT_ATTR_DUAL_SRESIDUAL_INDEX
  | GRB_INT_ATTR_DUAL_SVIO_INDEX
  | GRB_INT_ATTR_DUAL_VIO_INDEX
  | GRB_INT_ATTR_GENCONSTRTYPE
  | GRB_INT_ATTR_HASDUALNORM
  | GRB_INT_ATTR_IIS_CONSTR
  | GRB_INT_ATTR_IIS_GENCONSTR
  | GRB_INT_ATTR_IIS_LB
  | GRB_INT_ATTR_IIS_MINIMAL
  | GRB_INT_ATTR_IIS_QCONSTR
  | GRB_INT_ATTR_IIS_SOS
  | GRB_INT_ATTR_IIS_UB
  | GRB_INT_ATTR_INFEASVAR
  | GRB_INT_ATTR_INT_VIO_INDEX
  | GRB_INT_ATTR_IS_MIP
  | GRB_INT_ATTR_IS_QCP
  | GRB_INT_ATTR_IS_QP
  | GRB_INT_ATTR_LAZY
  | GRB_INT_ATTR_MODELSENSE
  | GRB_INT_ATTR_NUMBINVARS
  | GRB_INT_ATTR_NUMCONSTRS
  | GRB_INT_ATTR_NUMGENCONSTRS
  | GRB_INT_ATTR_NUMINTVARS
  | GRB_INT_ATTR_NUMNZS
  | GRB_INT_ATTR_NUMOBJ
  | GRB_INT_ATTR_NUMPWLOBJVARS
  | GRB_INT_ATTR_NUMQCNZS
  | GRB_INT_ATTR_NUMQCONSTRS
  | GRB_INT_ATTR_NUMQNZS
  | GRB_INT_ATTR_NUMSOS
  | GRB_INT_ATTR_NUMVARS
  | GRB_INT_ATTR_OBJNPRIORITY
  | GRB_INT_ATTR_PWLOBJCVX
  | GRB_INT_ATTR_SOLCOUNT
  | GRB_INT_ATTR_STATUS
  | GRB_INT_ATTR_TUNE_RESULTCOUNT
  | GRB_INT_ATTR_UNBDVAR
  | GRB_INT_ATTR_VARHINTPRI
  | GRB_INT_ATTR_VARPRESTAT
  | GRB_INT_ATTR_VBASIS

type strAttr =
  | GRB_STR_ATTR_CONSTRNAME
  | GRB_STR_ATTR_GENCONSTRNAME
  | GRB_STR_ATTR_MODELNAME
  | GRB_STR_ATTR_OBJNNAME
  | GRB_STR_ATTR_QCNAME
  | GRB_STR_ATTR_SERVER
  | GRB_STR_ATTR_VARNAME
